## Opening files

In [2]:
import pandas as pd

In [3]:
# queries

query_df = pd.read_xml("../data/kid-friend-en/en/inputs/topics.xml")
query_df.drop_duplicates(inplace=True, ignore_index=True)
query_df = query_df.rename({"number":"qid"}, axis=1)
query_df["query"] = ["".join([x if x.isalnum() else " " for x in query]) for query in query_df["query"]] # removing punctuations
query_df["qid"] = query_df["qid"].astype(str)
query_df.to_csv("../data/kid-friend-en/en/inputs/topics.csv", index=False)
query_df.head()

,qid,query,category,description,narrative
0,1,BTS,entertainment,Who are BTS? Where can I find their music?,Relevant documents for this request should inc...
1,2,BTS Bias Quiz,entertainment,Which band member suits me best? Which band me...,Relevant documents include kid-friendly conten...
2,3,BTS merch,entertainment,official BTS merch page and authorized sellers,Relevant documents redirect to fan articles of...
3,4,BTS Jungkook,entertainment,Who is Jungkook? What does he like? What does ...,Relevant documents contain information about J...
4,5,Minecraft,entertainment,What is Minecraft? Where can I play it? Let's ...,Relevant documents contain information about t...

In [18]:
# graded topical relevance

with open("../data/kid-friend-en/en/qrels/qrels-relevance.txt", "r") as f_qrel:
    lines= f_qrel.readlines()

qrels = []
for line in lines:
    qid, q0, docno, relevance = line.split(" ")
    qid = int(qid)
    relevance = int(relevance)
    qrels.append([qid, q0, docno, relevance])

qrels_df = pd.DataFrame(qrels, columns=["qid", "q0", "docno", "relevance"])
qrels_df["qid"] = qrels_df["qid"].astype(str)
print(len(qrels_df))
qrels_df.drop_duplicates(inplace=True, ignore_index=True)
print(len(qrels_df))

2303
2303

In [19]:
qrels_df = qrels_df.drop_duplicates(subset=["qid", "docno"], ignore_index=True, keep=False) # dropping qrels which have multiple relavances for a given (qid, docno) pair
len(qrels_df)

2303

In [20]:
qrels_df.to_csv("../data/kid-friend-en/en/qrels/qrels-relevance-graded.csv", index=False)
qrels_df.head()

  qid q0                             docno  relevance
0   1  0  77cdd0f6c3b04b5bbe79fac37c2ae63b          0
1   1  0  c8a2aa042145402a8c180ca6f467c575          1
2   1  0  d82e5e4f531841d49bcd6fe7bd8cdf8f          0
3   1  0  c8e3ba8d611441bebaf146001171af3a          1
4   1  0  44d7a109cd554b1cb44d2c3867ff7040          1

In [8]:
# binary topical relevance

qrels_df["relevance"] = [int(rel > 0) for rel in qrels_df["relevance"]]
qrels_df.to_csv("../data/kid-friend-en/en/qrels/qrels-relevance-binary.csv", index=False)
qrels_df.head()

  qid q0                             docno  relevance
0   1  0  77cdd0f6c3b04b5bbe79fac37c2ae63b          0
1   1  0  c8a2aa042145402a8c180ca6f467c575          1
2   1  0  d82e5e4f531841d49bcd6fe7bd8cdf8f          0
3   1  0  c8e3ba8d611441bebaf146001171af3a          1
4   1  0  44d7a109cd554b1cb44d2c3867ff7040          1

In [9]:
qrels_df.dtypes

qid          object
q0           object
docno        object
relevance     int64
dtype: object

In [10]:
query_df.dtypes

qid            object
query          object
category       object
description    object
narrative      object
dtype: object

In [1]:
import pandas as pd

df = pd.read_csv("../data/kid-friend-en/en/qrels/qrels-relevance-binary.csv")
df["relevance"].value_counts()

relevance
1    1480
0     823
Name: count, dtype: int64

## Adding more document features

### Readability

In [2]:
# adding readability (spache-allen) scores of documents

import json
import pandas as pd
from spache_allen.formula import spache_allen
from tqdm import tqdm

lines = []
with open(r'../data/kid-friend-en/en/inputs/documents.jsonl') as f:
    lines = f.read().splitlines()

line_dicts = [json.loads(line) for line in lines]
corpus = pd.DataFrame(line_dicts)
corpus.drop_duplicates(inplace=True,ignore_index=True)
corpus["readability"] = [spache_allen(text) for text in tqdm(corpus["snippet"], total=len(corpus))]
corpus.to_csv("../data/kid-friend-en/en/inputs/documents.csv", index=False)
print(len(corpus))
corpus.head()

  0%|          | 0/2385 [00:00<?, ?it/s]
  0%|          | 1/2385 [00:00<04:32,  8.75it/s]
  0%|          | 10/2385 [00:00<00:46, 51.37it/s]
  1%|          | 19/2385 [00:00<00:35, 65.80it/s]
  1%|          | 28/2385 [00:00<00:32, 71.87it/s]
  2%|▏         | 37/2385 [00:00<00:30, 75.77it/s]
  2%|▏         | 46/2385 [00:00<00:29, 78.53it/s]
  2%|▏         | 55/2385 [00:00<00:28, 80.46it/s]
  3%|▎         | 64/2385 [00:00<00:28, 81.57it/s]
  3%|▎         | 73/2385 [00:00<00:28, 82.37it/s]
  3%|▎         | 82/2385 [00:01<00:27, 82.55it/s]
  4%|▍         | 91/2385 [00:01<00:27, 83.44it/s]
  4%|▍         | 100/2385 [00:01<00:27, 83.76it/s]
  5%|▍         | 109/2385 [00:01<00:27, 84.07it/s]
  5%|▍         | 118/2385 [00:01<00:27, 83.89it/s]
  5%|▌         | 127/2385 [00:01<00:27, 83.17it/s]
  6%|▌         | 136/2385 [00:01<00:26, 83.44it/s]
  6%|▌         | 145/2385 [00:01<00:26, 83.41it/s]
  6%|▋         | 154/2385 [00:01<00:26, 83.92it/s]
  7%|▋         | 163/2385 [00:02<00:26, 84.31it/s]
  7%|▋         | 172/2385 [00:02<00:26, 84.40it/s]
  8%|▊         | 181/2385 [00:02<00:26, 83.44it/s]
  8%|▊         | 190/2385 [00:02<00:26, 83.87it/s]
  8%|▊         | 199/2385 [00:02<00:26, 83.97it/s]
  9%|▊         | 208/2385 [00:02<00:25, 83.82it/s]
  9%|▉         | 217/2385 [00:02<00:25, 83.99it/s]
  9%|▉         | 226/2385 [00:02<00:25, 84.28it/s]
 10%|▉         | 235/2385 [00:02<00:25, 84.01it/s]
 10%|█         | 244/2385 [00:03<00:25, 83.91it/s]
 11%|█         | 253/2385 [00:03<00:25, 83.60it/s]
 11%|█         | 262/2385 [00:03<00:25, 83.70it/s]
 11%|█▏        | 271/2385 [00:03<00:25, 83.83it/s]
 12%|█▏        | 280/2385 [00:03<00:25, 83.96it/s]
 12%|█▏        | 289/2385 [00:03<00:24, 84.02it/s]
 12%|█▏        | 298/2385 [00:03<00:24, 84.13it/s]
 13%|█▎        | 307/2385 [00:03<00:24, 84.42it/s]
 13%|█▎        | 316/2385 [00:03<00:24, 84.81it/s]
 14%|█▎        | 325/2385 [00:03<00:24, 84.60it/s]
 14%|█▍        | 334/2385 [00:04<00:24, 83.72it/s]
 14%|█▍        | 343/2385 [00:04<00:24, 83.62it/s]
 15%|█▍        | 352/2385 [00:04<00:24, 83.43it/s]
 15%|█▌        | 361/2385 [00:04<00:24, 83.57it/s]
 16%|█▌        | 370/2385 [00:04<00:24, 83.71it/s]
 16%|█▌        | 379/2385 [00:04<00:23, 83.91it/s]
 16%|█▋        | 388/2385 [00:04<00:23, 83.60it/s]
 17%|█▋        | 397/2385 [00:04<00:23, 83.69it/s]
 17%|█▋        | 406/2385 [00:04<00:23, 83.74it/s]
 17%|█▋        | 415/2385 [00:05<00:23, 83.86it/s]
 18%|█▊        | 424/2385 [00:05<00:23, 83.91it/s]
 18%|█▊        | 433/2385 [00:05<00:23, 83.59it/s]
 19%|█▊        | 442/2385 [00:05<00:23, 83.94it/s]
 19%|█▉        | 451/2385 [00:05<00:23, 84.04it/s]
 19%|█▉        | 460/2385 [00:05<00:22, 84.10it/s]
 20%|█▉        | 469/2385 [00:05<00:23, 83.26it/s]
 20%|██        | 478/2385 [00:05<00:22, 83.67it/s]
 20%|██        | 487/2385 [00:05<00:22, 82.93it/s]
 21%|██        | 496/2385 [00:06<00:22, 83.18it/s]
 21%|██        | 505/2385 [00:06<00:22, 83.38it/s]
 22%|██▏       | 514/2385 [00:06<00:22, 83.28it/s]
 22%|██▏       | 523/2385 [00:06<00:22, 83.70it/s]
 22%|██▏       | 532/2385 [00:06<00:22, 83.72it/s]
 23%|██▎       | 541/2385 [00:06<00:22, 83.75it/s]
 23%|██▎       | 550/2385 [00:06<00:21, 83.65it/s]
 23%|██▎       | 559/2385 [00:06<00:21, 83.47it/s]
 24%|██▍       | 568/2385 [00:06<00:21, 83.42it/s]
 24%|██▍       | 577/2385 [00:06<00:21, 83.82it/s]
 25%|██▍       | 586/2385 [00:07<00:21, 83.81it/s]
 25%|██▍       | 595/2385 [00:07<00:21, 83.96it/s]
 25%|██▌       | 604/2385 [00:07<00:21, 83.76it/s]
 26%|██▌       | 613/2385 [00:07<00:21, 83.62it/s]
 26%|██▌       | 622/2385 [00:07<00:21, 83.50it/s]
 26%|██▋       | 631/2385 [00:07<00:21, 82.92it/s]
 27%|██▋       | 640/2385 [00:07<00:21, 82.21it/s]
 27%|██▋       | 649/2385 [00:07<00:21, 82.59it/s]
 28%|██▊       | 658/2385 [00:07<00:20, 83.07it/s]
 28%|██▊       | 667/2385 [00:08<00:20, 83.17it/s]
 28%|██▊       | 676/2385 [00:08<00:20, 83.33it/s]
 29%|██▊       | 685/2385 [00:08<00:20, 83.50it/s]
 29%|██▉       | 694/2385 [00:08<00:20, 83.41it/s]
 29%|██▉       | 703/2385 [00:08<00:20, 83.70it/s]
 30%|██▉       | 712/2385 [00:08<00:20, 83.46it/s]
 30%|███       | 721/2385 [00:08<00:19, 83.97it/s]
 31%|███       | 730/2385 [00:08<00:19, 83.78it/s]
 31%|███       | 739/2385 [00:08<00:19, 83.83it/s]
 31%|███▏      | 748/2385 [00:09<00:19, 83.62it/s]
 32%|███▏      | 757/2385 [00:09<00:19, 83.37it/s]
 32%|███▏      | 766/2385 [00:09<00:19, 82.97it/s]
 32%|███▏      | 775/2385 [00:09<00:19, 82.95it/s]
 33%|███▎      | 784/2385 [00:09<00:19, 83.11it/s]
 33%|███▎      | 793/2385 [00:09<00:19, 82.26it/s]
 34%|███▎      | 802/2385 [00:09<00:19, 82.49it/s]
 34%|███▍      | 811/2385 [00:09<00:19, 82.73it/s]
 34%|███▍      | 820/2385 [00:09<00:18, 83.05it/s]
 35%|███▍      | 829/2385 [00:10<00:18, 83.46it/s]
 35%|███▌      | 838/2385 [00:10<00:18, 83.72it/s]
 36%|███▌      | 847/2385 [00:10<00:18, 83.64it/s]
 36%|███▌      | 856/2385 [00:10<00:18, 84.09it/s]
 36%|███▋      | 865/2385 [00:10<00:18, 84.31it/s]
 37%|███▋      | 874/2385 [00:10<00:17, 84.28it/s]
 37%|███▋      | 883/2385 [00:10<00:17, 84.79it/s]
 37%|███▋      | 892/2385 [00:10<00:17, 84.96it/s]
 38%|███▊      | 901/2385 [00:10<00:17, 84.65it/s]
 38%|███▊      | 910/2385 [00:10<00:17, 84.37it/s]
 39%|███▊      | 919/2385 [00:11<00:17, 84.03it/s]
 39%|███▉      | 928/2385 [00:11<00:17, 84.16it/s]
 39%|███▉      | 937/2385 [00:11<00:17, 84.17it/s]
 40%|███▉      | 946/2385 [00:11<00:17, 83.20it/s]
 40%|████      | 955/2385 [00:11<00:17, 83.35it/s]
 40%|████      | 964/2385 [00:11<00:17, 83.36it/s]
 41%|████      | 973/2385 [00:11<00:16, 83.50it/s]
 41%|████      | 982/2385 [00:11<00:16, 82.72it/s]
 42%|████▏     | 991/2385 [00:11<00:16, 83.04it/s]
 42%|████▏     | 1000/2385 [00:12<00:16, 83.44it/s]
 42%|████▏     | 1009/2385 [00:12<00:16, 83.91it/s]
 43%|████▎     | 1018/2385 [00:12<00:16, 84.11it/s]
 43%|████▎     | 1027/2385 [00:12<00:16, 84.47it/s]
 43%|████▎     | 1036/2385 [00:12<00:15, 84.82it/s]
 44%|████▍     | 1045/2385 [00:12<00:15, 84.28it/s]
 44%|████▍     | 1054/2385 [00:12<00:15, 84.83it/s]
 45%|████▍     | 1063/2385 [00:12<00:15, 85.34it/s]
 45%|████▍     | 1072/2385 [00:12<00:15, 85.44it/s]
 45%|████▌     | 1081/2385 [00:13<00:15, 85.22it/s]
 46%|████▌     | 1090/2385 [00:13<00:15, 84.96it/s]
 46%|████▌     | 1099/2385 [00:13<00:15, 83.97it/s]
 46%|████▋     | 1108/2385 [00:13<00:15, 82.47it/s]
 47%|████▋     | 1117/2385 [00:13<00:15, 82.12it/s]
 47%|████▋     | 1126/2385 [00:13<00:15, 82.45it/s]
 48%|████▊     | 1135/2385 [00:13<00:15, 82.51it/s]
 48%|████▊     | 1144/2385 [00:13<00:14, 83.30it/s]
 48%|████▊     | 1153/2385 [00:13<00:14, 83.72it/s]
 49%|████▊     | 1162/2385 [00:13<00:14, 83.34it/s]
 49%|████▉     | 1171/2385 [00:14<00:14, 83.54it/s]
 49%|████▉     | 1180/2385 [00:14<00:14, 83.90it/s]
 50%|████▉     | 1189/2385 [00:14<00:14, 84.26it/s]
 50%|█████     | 1198/2385 [00:14<00:14, 84.40it/s]
 51%|█████     | 1207/2385 [00:14<00:13, 84.31it/s]
 51%|█████     | 1216/2385 [00:14<00:13, 84.22it/s]
 51%|█████▏    | 1225/2385 [00:14<00:13, 84.12it/s]
 52%|█████▏    | 1234/2385 [00:14<00:13, 84.19it/s]
 52%|█████▏    | 1243/2385 [00:14<00:13, 84.21it/s]
 52%|█████▏    | 1252/2385 [00:15<00:13, 83.01it/s]
 53%|█████▎    | 1261/2385 [00:15<00:13, 82.97it/s]
 53%|█████▎    | 1270/2385 [00:15<00:13, 83.01it/s]
 54%|█████▎    | 1279/2385 [00:15<00:13, 83.26it/s]
 54%|█████▍    | 1288/2385 [00:15<00:13, 83.58it/s]
 54%|█████▍    | 1297/2385 [00:15<00:12, 83.87it/s]
 55%|█████▍    | 1306/2385 [00:15<00:12, 83.93it/s]
 55%|█████▌    | 1315/2385 [00:15<00:12, 83.73it/s]
 56%|█████▌    | 1324/2385 [00:15<00:12, 83.90it/s]
 56%|█████▌    | 1333/2385 [00:16<00:12, 83.39it/s]
 56%|█████▋    | 1342/2385 [00:16<00:12, 83.22it/s]
 57%|█████▋    | 1351/2385 [00:16<00:12, 82.37it/s]
 57%|█████▋    | 1360/2385 [00:16<00:12, 82.63it/s]
 57%|█████▋    | 1369/2385 [00:16<00:12, 83.19it/s]
 58%|█████▊    | 1378/2385 [00:16<00:11, 83.99it/s]
 58%|█████▊    | 1387/2385 [00:16<00:11, 84.38it/s]
 59%|█████▊    | 1396/2385 [00:16<00:11, 84.58it/s]
 59%|█████▉    | 1405/2385 [00:16<00:11, 84.36it/s]
 59%|█████▉    | 1414/2385 [00:16<00:11, 84.78it/s]
 60%|█████▉    | 1423/2385 [00:17<00:11, 85.07it/s]
 60%|██████    | 1432/2385 [00:17<00:11, 85.54it/s]
 60%|██████    | 1441/2385 [00:17<00:11, 84.91it/s]
 61%|██████    | 1450/2385 [00:17<00:10, 85.01it/s]
 61%|██████    | 1459/2385 [00:17<00:10, 85.30it/s]
 62%|██████▏   | 1468/2385 [00:17<00:10, 85.44it/s]
 62%|██████▏   | 1477/2385 [00:17<00:10, 85.39it/s]
 62%|██████▏   | 1486/2385 [00:17<00:10, 85.41it/s]
 63%|██████▎   | 1495/2385 [00:17<00:10, 85.61it/s]
 63%|██████▎   | 1504/2385 [00:18<00:10, 85.46it/s]
 63%|██████▎   | 1513/2385 [00:18<00:10, 85.88it/s]
 64%|██████▍   | 1522/2385 [00:18<00:10, 85.36it/s]
 64%|██████▍   | 1531/2385 [00:18<00:10, 85.16it/s]
 65%|██████▍   | 1540/2385 [00:18<00:09, 85.49it/s]
 65%|██████▍   | 1549/2385 [00:18<00:09, 85.40it/s]
 65%|██████▌   | 1558/2385 [00:18<00:09, 84.97it/s]
 66%|██████▌   | 1567/2385 [00:18<00:09, 85.13it/s]
 66%|██████▌   | 1576/2385 [00:18<00:09, 84.76it/s]
 66%|██████▋   | 1585/2385 [00:18<00:09, 85.24it/s]
 67%|██████▋   | 1594/2385 [00:19<00:09, 84.91it/s]
 67%|██████▋   | 1603/2385 [00:19<00:09, 85.31it/s]
 68%|██████▊   | 1612/2385 [00:19<00:09, 85.45it/s]
 68%|██████▊   | 1621/2385 [00:19<00:08, 84.92it/s]
 68%|██████▊   | 1630/2385 [00:19<00:08, 85.00it/s]
 69%|██████▊   | 1639/2385 [00:19<00:08, 84.88it/s]
 69%|██████▉   | 1648/2385 [00:19<00:08, 85.38it/s]
 69%|██████▉   | 1657/2385 [00:19<00:08, 85.53it/s]
 70%|██████▉   | 1666/2385 [00:19<00:08, 85.58it/s]
 70%|███████   | 1675/2385 [00:20<00:08, 85.68it/s]
 71%|███████   | 1684/2385 [00:20<00:08, 85.81it/s]
 71%|███████   | 1693/2385 [00:20<00:08, 85.71it/s]
 71%|███████▏  | 1702/2385 [00:20<00:07, 85.99it/s]
 72%|███████▏  | 1711/2385 [00:20<00:07, 85.63it/s]
 72%|███████▏  | 1720/2385 [00:20<00:07, 85.28it/s]
 72%|███████▏  | 1729/2385 [00:20<00:07, 85.95it/s]
 73%|███████▎  | 1738/2385 [00:20<00:07, 86.34it/s]
 73%|███████▎  | 1747/2385 [00:20<00:07, 86.90it/s]
 74%|███████▎  | 1756/2385 [00:20<00:07, 87.79it/s]
 74%|███████▍  | 1765/2385 [00:21<00:07, 87.47it/s]
 74%|███████▍  | 1774/2385 [00:21<00:06, 87.75it/s]
 75%|███████▍  | 1783/2385 [00:21<00:06, 87.39it/s]
 75%|███████▌  | 1792/2385 [00:21<00:06, 87.73it/s]
 76%|███████▌  | 1801/2385 [00:21<00:06, 87.30it/s]
 76%|███████▌  | 1810/2385 [00:21<00:06, 87.61it/s]
 76%|███████▋  | 1819/2385 [00:21<00:06, 88.27it/s]
 77%|███████▋  | 1828/2385 [00:21<00:06, 88.64it/s]
 77%|███████▋  | 1837/2385 [00:21<00:06, 87.91it/s]
 77%|███████▋  | 1846/2385 [00:22<00:06, 88.41it/s]
 78%|███████▊  | 1855/2385 [00:22<00:06, 88.29it/s]
 78%|███████▊  | 1864/2385 [00:22<00:05, 87.41it/s]
 79%|███████▊  | 1873/2385 [00:22<00:05, 86.81it/s]
 79%|███████▉  | 1882/2385 [00:22<00:05, 85.88it/s]
 79%|███████▉  | 1891/2385 [00:22<00:05, 86.11it/s]
 80%|███████▉  | 1900/2385 [00:22<00:05, 86.69it/s]
 80%|████████  | 1909/2385 [00:22<00:05, 87.59it/s]
 80%|████████  | 1918/2385 [00:22<00:05, 87.58it/s]
 81%|████████  | 1927/2385 [00:22<00:05, 87.76it/s]
 81%|████████  | 1936/2385 [00:23<00:05, 87.34it/s]
 82%|████████▏ | 1945/2385 [00:23<00:05, 87.34it/s]
 82%|████████▏ | 1954/2385 [00:23<00:04, 87.13it/s]
 82%|████████▏ | 1963/2385 [00:23<00:04, 86.64it/s]
 83%|████████▎ | 1972/2385 [00:23<00:04, 86.43it/s]
 83%|████████▎ | 1981/2385 [00:23<00:04, 85.95it/s]
 83%|████████▎ | 1990/2385 [00:23<00:04, 85.73it/s]
 84%|████████▍ | 1999/2385 [00:23<00:04, 85.78it/s]
 84%|████████▍ | 2008/2385 [00:23<00:04, 85.58it/s]
 85%|████████▍ | 2017/2385 [00:23<00:04, 84.63it/s]
 85%|████████▍ | 2026/2385 [00:24<00:04, 84.31it/s]
 85%|████████▌ | 2035/2385 [00:24<00:04, 82.91it/s]
 86%|████████▌ | 2044/2385 [00:24<00:04, 82.83it/s]
 86%|████████▌ | 2053/2385 [00:24<00:03, 83.03it/s]
 86%|████████▋ | 2062/2385 [00:24<00:03, 83.16it/s]
 87%|████████▋ | 2071/2385 [00:24<00:03, 83.24it/s]
 87%|████████▋ | 2080/2385 [00:24<00:03, 83.52it/s]
 88%|████████▊ | 2089/2385 [00:24<00:03, 83.55it/s]
 88%|████████▊ | 2098/2385 [00:24<00:03, 83.44it/s]
 88%|████████▊ | 2107/2385 [00:25<00:03, 83.29it/s]
 89%|████████▊ | 2116/2385 [00:25<00:03, 83.60it/s]
 89%|████████▉ | 2125/2385 [00:25<00:03, 83.34it/s]
 89%|████████▉ | 2134/2385 [00:25<00:03, 83.66it/s]
 90%|████████▉ | 2143/2385 [00:25<00:02, 84.02it/s]
 90%|█████████ | 2152/2385 [00:25<00:02, 83.67it/s]
 91%|█████████ | 2161/2385 [00:25<00:02, 83.62it/s]
 91%|█████████ | 2170/2385 [00:25<00:02, 83.93it/s]
 91%|█████████▏| 2179/2385 [00:25<00:02, 84.34it/s]
 92%|█████████▏| 2188/2385 [00:26<00:02, 83.54it/s]
 92%|█████████▏| 2197/2385 [00:26<00:02, 83.72it/s]
 92%|█████████▏| 2206/2385 [00:26<00:02, 83.84it/s]
 93%|█████████▎| 2215/2385 [00:26<00:02, 83.73it/s]
 93%|█████████▎| 2224/2385 [00:26<00:01, 83.52it/s]
 94%|█████████▎| 2233/2385 [00:26<00:01, 83.32it/s]
 94%|█████████▍| 2242/2385 [00:26<00:01, 82.86it/s]
 94%|█████████▍| 2251/2385 [00:26<00:01, 83.50it/s]
 95%|█████████▍| 2260/2385 [00:26<00:01, 83.45it/s]
 95%|█████████▌| 2269/2385 [00:27<00:01, 83.76it/s]
 96%|█████████▌| 2278/2385 [00:27<00:01, 84.01it/s]
 96%|█████████▌| 2287/2385 [00:27<00:01, 84.27it/s]
 96%|█████████▋| 2296/2385 [00:27<00:01, 84.05it/s]
 97%|█████████▋| 2305/2385 [00:27<00:00, 84.44it/s]
 97%|█████████▋| 2314/2385 [00:27<00:00, 84.68it/s]
 97%|█████████▋| 2323/2385 [00:27<00:00, 85.07it/s]
 98%|█████████▊| 2332/2385 [00:27<00:00, 84.94it/s]
 98%|█████████▊| 2341/2385 [00:27<00:00, 83.37it/s]
 99%|█████████▊| 2350/2385 [00:27<00:00, 83.94it/s]
 99%|█████████▉| 2359/2385 [00:28<00:00, 83.88it/s]
 99%|█████████▉| 2368/2385 [00:28<00:00, 84.36it/s]
100%|██████████| 2385/2385 [00:28<00:00, 84.02it/s]

2385

,docno,snippet,title,main_content,readability
0,6e421f1539b1457b853712d81be87743,WEBBTS (also Bangtan Boys; Korean: 방탄소년단 Bangt...,BTS (band) - Wikipedia,BTS (also Bangtan Boys; Korean: 방탄소년단 Bangtan ...,8.476857
1,1539268e3f1d41c9abcaa277b23f51d9,WEBMusic video by BTS performing Dynamite. (C)...,Before you go on to YouTube,YouTube\nA Google company\n\nBefore you go on ...,5.729500
2,93689ea1c0ec4272b41d7b259cb47890,Biography BTS is a Grammy-nominated South Kore...,Before you go on to YouTube,YouTube\nA Google company\n\nBefore you go on ...,6.051250
3,2e4321c5105840c8b6612f87dc4aba13,WEBBTS (Korean: 방탄소년단; RR: Bangtan Sonyeondan;...,BTS - Wikipedia,BTS (Korean방탄소년단; RRBangtan Sonyeondan; lit. B...,6.293952
4,3d21474fff4e406c9db2984d5edf647b,"WEBTo avoid this, cancel and sign in to YouTub...",BTS (방탄소년단) 'Yet To Come (The Most Beautiful M...,"So, Who is missing BTS badly. Let's stay stron...",5.167517

In [3]:
import pandas as pd

df = pd.read_csv("../data/kid-friend-en/en/inputs/documents.csv")
len(df)

2385

In [4]:
import pandas as pd
import json

lines = []
with open(r'../data/kid-friend-en/en/inputs/documents.jsonl') as f:
    lines = f.read().splitlines()

line_dicts = [json.loads(line) for line in lines]
corpus = pd.DataFrame(line_dicts)
corpus.drop_duplicates(inplace=True,ignore_index=True)
len(corpus.loc[corpus["main_content"]==""]), len(corpus.loc[(corpus["main_content"]=="")&(corpus["snippet"]=="")]), len(corpus.loc[(corpus["main_content"]=="")&(corpus["snippet"]=="")&(corpus["title"]=="")])

(187, 15, 7)

In [5]:
corpus_df = pd.read_csv("../data/kid-friend-en/en/inputs/documents.csv")
corpus_df.loc[(corpus_df["readability"]<0)&(corpus_df["main_content"].isna()==False)]

,docno,snippet,title,main_content,readability
1144,b0687fecdf9d477e833963defdf74e10,www.klimakleber.org,NaN,"climateglue.org\nis parked free, courtesy of G...",-1.0
1711,9fb79a165532437fb5d814a8a0784991,NaN,지민 (Jimin) 'Who' Official MV - YouTube,매일매일 수십번을 들어도 넘 좋은 WHO 진짜 고마워 지민 언제나 행복하게 기다리고...,-1.0
1712,5240a343b77c4428ba7d87bd092d02f6,NaN,NaN,BTS member Jin finishes military service - ban...,-1.0
1713,10727b9260ea4250a3576209aa40de2e,NaN,Amazon.com,Enter the characters below\n\nWe ask for your ...,-1.0
1714,3cca2583656a4c528dcc6b8213b5bdd7,NaN,BTS (Bangtan Boys) | BTS Wiki | Fandom,BTS Wiki\nAdvertisement\n\nBTS short info[]\n\...,-1.0
...,...,...,...,...,...
1952,9b416a567f5b4bb0bc2ce99cd2ab1e25,NaN,All about the first period during puberty | o.b.®,The first period\n\nWomen laugh and make faces...,-1.0
1953,3fcf27e780f147ae96e799b5e3832615,NaN,\n How do I know when I'm getting my period? ...,How do I feel that I am getting my period?\n\n...,-1.0
1962,3a667ab4ded14e8891d0180e2944a1bb,NaN,planet schule: How do breasts change during pu...,planet schule: How do breasts change during pu...,-1.0
1973,ae64d77ebaf74ee1839dc1557defa3a3,NaN,Recognize if a boy likes you,Magazine\n\nOverview of\nFilter:\n - icon30\n...,-1.0
1984,333fdd2f08234b25a2a61b44470cad01,NaN,What are 5 subtle signs that a girl likes you?...,Sort\n\nShe touches you seemingly at random wh...,-1.0

In [6]:
corpus_df.loc[(corpus_df["readability"]<0)]

,docno,snippet,title,main_content,readability
1144,b0687fecdf9d477e833963defdf74e10,www.klimakleber.org,NaN,"climateglue.org\nis parked free, courtesy of G...",-1.0
1181,161338fc0d0c4385a973f9d861940566,NaN,Log in to X / X,NaN,-1.0
1709,c83695f0502b486086d939f3d15d9478,NaN,BTS (방탄소년단) 'Dynamite' Official MV - YouTube,NaN,-1.0
1711,9fb79a165532437fb5d814a8a0784991,NaN,지민 (Jimin) 'Who' Official MV - YouTube,매일매일 수십번을 들어도 넘 좋은 WHO 진짜 고마워 지민 언제나 행복하게 기다리고...,-1.0
1712,5240a343b77c4428ba7d87bd092d02f6,NaN,NaN,BTS member Jin finishes military service - ban...,-1.0
...,...,...,...,...,...
1962,3a667ab4ded14e8891d0180e2944a1bb,NaN,planet schule: How do breasts change during pu...,planet schule: How do breasts change during pu...,-1.0
1973,ae64d77ebaf74ee1839dc1557defa3a3,NaN,Recognize if a boy likes you,Magazine\n\nOverview of\nFilter:\n - icon30\n...,-1.0
1979,c2a251b89e224009ac1765bf4dd1d395,NaN,10 cute things boys LOVE when girls do them! -...,NaN,-1.0
1984,333fdd2f08234b25a2a61b44470cad01,NaN,What are 5 subtle signs that a girl likes you?...,Sort\n\nShe touches you seemingly at random wh...,-1.0
1990,db2c3a6083564168ba7e5ae615ecbd9d,NaN,What GIRLS LOVE about boys 😏 - YouTube,NaN,-1.0

### Objectivity

In [8]:
import json
import pandas as pd
from utils import get_obj_likelihood
from make_predictions import generate_predictions
from tqdm import tqdm

lines = []
with open(r'../data/kid-friend-en/en/inputs/documents.jsonl') as f:
    lines = f.read().splitlines()

line_dicts = [json.loads(line) for line in lines]
corpus = pd.DataFrame(line_dicts)
corpus.drop_duplicates(inplace=True,ignore_index=True)
corpus["obj_prob"] = get_obj_likelihood(list(corpus["snippet"]))
corpus = corpus[["docno","obj_prob"]]

corpus_df = pd.read_csv("../data/kid-friend-en/en/inputs/documents.csv")
corpus_df = corpus_df.merge(corpus, on="docno")
corpus_df.to_csv("../data/kid-friend-en/en/inputs/documents.csv", index=False)
corpus_df.head()

# generate_predictions()

Device set to use cuda:0

,docno,snippet,title,main_content,readability,obj_prob
0,6e421f1539b1457b853712d81be87743,WEBBTS (also Bangtan Boys; Korean: 방탄소년단 Bangt...,BTS (band) - Wikipedia,BTS (also Bangtan Boys; Korean: 방탄소년단 Bangtan ...,8.476857,0.876282
1,1539268e3f1d41c9abcaa277b23f51d9,WEBMusic video by BTS performing Dynamite. (C)...,Before you go on to YouTube,YouTube\nA Google company\n\nBefore you go on ...,5.729500,0.846696
2,93689ea1c0ec4272b41d7b259cb47890,Biography BTS is a Grammy-nominated South Kore...,Before you go on to YouTube,YouTube\nA Google company\n\nBefore you go on ...,6.051250,0.895289
3,2e4321c5105840c8b6612f87dc4aba13,WEBBTS (Korean: 방탄소년단; RR: Bangtan Sonyeondan;...,BTS - Wikipedia,BTS (Korean방탄소년단; RRBangtan Sonyeondan; lit. B...,6.293952,0.876808
4,3d21474fff4e406c9db2984d5edf647b,"WEBTo avoid this, cancel and sign in to YouTub...",BTS (방탄소년단) 'Yet To Come (The Most Beautiful M...,"So, Who is missing BTS badly. Let's stay stron...",5.167517,0.615062

In [5]:
# import numpy as np

# lines = []
# with open(r'../data/kid-friend-en/en/inputs/documents.jsonl') as f:
#     lines = f.read().splitlines()

# line_dicts = [json.loads(line) for line in lines]
# corpus = pd.DataFrame(line_dicts)

# np.argmax([len(text) for text in corpus['main_content']])

np.int64(1100)

In [6]:
# corpus.iloc[1100]

docno                            a5619809b4a34347a8cf77a6b8b72211
snippet         A coral reef is an underwater ecosystem charac...
title                                      Coral reef - Wikipedia
main_content    Jump to content\n\nCoral reef\n\nPage semi-pro...
Name: 1100, dtype: object

### Educational Alignment

In [9]:
import json
import pandas as pd
from tqdm import tqdm
from utils import get_edu_value

lines = []
with open(r'../data/kid-friend-en/en/inputs/documents.jsonl') as f:
    lines = f.read().splitlines()

line_dicts = [json.loads(line) for line in lines]
corpus = pd.DataFrame(line_dicts)
corpus.drop_duplicates(inplace=True,ignore_index=True)
corpus["edu_val"] = [get_edu_value(text) for text in tqdm(corpus["snippet"], total=len(corpus))]

corpus = corpus[["docno","edu_val"]]
corpus_df = pd.read_csv("../data/kid-friend-en/en/inputs/documents.csv")
corpus_df = corpus_df.merge(corpus, on="docno")
corpus_df.to_csv("../data/kid-friend-en/en/inputs/documents.csv", index=False)
corpus_df.head()

  0%|          | 0/2385 [00:00<?, ?it/s]
  0%|          | 1/2385 [00:09<6:10:14,  9.32s/it]
  0%|          | 2/2385 [00:10<2:53:19,  4.36s/it]
  0%|          | 3/2385 [00:11<1:51:55,  2.82s/it]
  0%|          | 4/2385 [00:12<1:27:31,  2.21s/it]
  0%|          | 5/2385 [00:13<1:10:02,  1.77s/it]
  0%|          | 6/2385 [00:14<58:16,  1.47s/it]
  0%|          | 7/2385 [00:15<50:24,  1.27s/it]
  0%|          | 8/2385 [00:16<45:29,  1.15s/it]
  0%|          | 9/2385 [00:16<42:23,  1.07s/it]
  0%|          | 10/2385 [00:17<40:02,  1.01s/it]
  0%|          | 11/2385 [00:18<38:31,  1.03it/s]
  1%|          | 12/2385 [00:20<43:40,  1.10s/it]
  1%|          | 13/2385 [00:21<42:27,  1.07s/it]
  1%|          | 14/2385 [00:22<40:16,  1.02s/it]
  1%|          | 15/2385 [00:22<38:59,  1.01it/s]
  1%|          | 16/2385 [00:23<37:45,  1.05it/s]
  1%|          | 17/2385 [00:24<37:07,  1.06it/s]
  1%|          | 18/2385 [00:25<36:26,  1.08it/s]
  1%|          | 19/2385 [00:26<36:11,  1.09it/s]
  1%|          | 20/2385 [00:27<35:57,  1.10it/s]
  1%|          | 21/2385 [00:28<35:33,  1.11it/s]
  1%|          | 22/2385 [00:29<35:35,  1.11it/s]
  1%|          | 23/2385 [00:30<35:14,  1.12it/s]
  1%|          | 24/2385 [00:31<35:12,  1.12it/s]
  1%|          | 25/2385 [00:31<35:04,  1.12it/s]
  1%|          | 26/2385 [00:32<35:20,  1.11it/s]
  1%|          | 27/2385 [00:33<35:32,  1.11it/s]
  1%|          | 28/2385 [00:34<35:16,  1.11it/s]
  1%|          | 29/2385 [00:35<35:19,  1.11it/s]
  1%|▏         | 30/2385 [00:36<35:12,  1.11it/s]
  1%|▏         | 31/2385 [00:37<35:19,  1.11it/s]
  1%|▏         | 32/2385 [00:38<37:03,  1.06it/s]
  1%|▏         | 33/2385 [00:39<36:30,  1.07it/s]
  1%|▏         | 34/2385 [00:40<35:59,  1.09it/s]
  1%|▏         | 35/2385 [00:41<35:45,  1.10it/s]
  2%|▏         | 36/2385 [00:41<35:55,  1.09it/s]
  2%|▏         | 37/2385 [00:42<35:40,  1.10it/s]
  2%|▏         | 38/2385 [00:43<36:02,  1.09it/s]
  2%|▏         | 39/2385 [00:44<35:50,  1.09it/s]
  2%|▏         | 40/2385 [00:45<35:31,  1.10it/s]
  2%|▏         | 41/2385 [00:46<40:09,  1.03s/it]
  2%|▏         | 42/2385 [00:47<38:30,  1.01it/s]
  2%|▏         | 43/2385 [00:48<37:35,  1.04it/s]
  2%|▏         | 44/2385 [00:49<37:00,  1.05it/s]
  2%|▏         | 45/2385 [00:50<37:22,  1.04it/s]
  2%|▏         | 46/2385 [00:51<36:54,  1.06it/s]
  2%|▏         | 47/2385 [00:52<36:11,  1.08it/s]
  2%|▏         | 48/2385 [00:53<35:42,  1.09it/s]
  2%|▏         | 49/2385 [00:54<35:31,  1.10it/s]
  2%|▏         | 50/2385 [00:55<40:06,  1.03s/it]
  2%|▏         | 51/2385 [00:56<38:33,  1.01it/s]
  2%|▏         | 52/2385 [00:57<37:32,  1.04it/s]
  2%|▏         | 53/2385 [00:58<36:56,  1.05it/s]
  2%|▏         | 54/2385 [00:59<36:27,  1.07it/s]
  2%|▏         | 55/2385 [01:00<36:01,  1.08it/s]
  2%|▏         | 56/2385 [01:00<35:58,  1.08it/s]
  2%|▏         | 57/2385 [01:01<35:39,  1.09it/s]
  2%|▏         | 58/2385 [01:02<35:26,  1.09it/s]
  2%|▏         | 59/2385 [01:03<35:15,  1.10it/s]
  3%|▎         | 60/2385 [01:04<35:06,  1.10it/s]
  3%|▎         | 61/2385 [01:05<35:14,  1.10it/s]
  3%|▎         | 62/2385 [01:06<34:49,  1.11it/s]
  3%|▎         | 63/2385 [01:07<34:50,  1.11it/s]
  3%|▎         | 64/2385 [01:08<36:50,  1.05it/s]
  3%|▎         | 65/2385 [01:09<36:02,  1.07it/s]
  3%|▎         | 66/2385 [01:10<35:33,  1.09it/s]
  3%|▎         | 67/2385 [01:11<35:14,  1.10it/s]
  3%|▎         | 68/2385 [01:11<35:27,  1.09it/s]
  3%|▎         | 69/2385 [01:12<36:00,  1.07it/s]
  3%|▎         | 70/2385 [01:13<35:36,  1.08it/s]
  3%|▎         | 71/2385 [01:14<35:31,  1.09it/s]
  3%|▎         | 72/2385 [01:15<35:09,  1.10it/s]
  3%|▎         | 73/2385 [01:16<34:54,  1.10it/s]
  3%|▎         | 74/2385 [01:17<34:40,  1.11it/s]
  3%|▎         | 75/2385 [01:18<35:03,  1.10it/s]
  3%|▎         | 76/2385 [01:19<35:08,  1.09it/s]
  3%|▎         | 77/2385 [01:20<34:46,  1.11it/s]
  3%|▎         | 78/2385 [01:21<34:37,  1.11it/s]
  3%|▎         | 79/2385 [01:21<34:42,  1.11it/s]
  3%|▎         | 80/2385 [01:22<34:53,  1.10it/s]
  3%|▎         | 81/2385 [01:23<34:44,  1.11it/s]
  3%|▎         | 82/2385 [01:24<34:36,  1.11it/s]
  3%|▎         | 83/2385 [01:25<34:54,  1.10it/s]
  4%|▎         | 84/2385 [01:26<36:34,  1.05it/s]
  4%|▎         | 85/2385 [01:27<35:47,  1.07it/s]
  4%|▎         | 86/2385 [01:28<37:12,  1.03it/s]
  4%|▎         | 87/2385 [01:29<36:24,  1.05it/s]
  4%|▎         | 88/2385 [01:30<36:47,  1.04it/s]
  4%|▎         | 89/2385 [01:31<36:04,  1.06it/s]
  4%|▍         | 90/2385 [01:32<35:31,  1.08it/s]
  4%|▍         | 91/2385 [01:33<35:28,  1.08it/s]
  4%|▍         | 92/2385 [01:34<35:15,  1.08it/s]
  4%|▍         | 93/2385 [01:35<35:18,  1.08it/s]
  4%|▍         | 94/2385 [01:35<35:00,  1.09it/s]
  4%|▍         | 95/2385 [01:36<34:59,  1.09it/s]
  4%|▍         | 96/2385 [01:37<34:44,  1.10it/s]
  4%|▍         | 97/2385 [01:38<34:59,  1.09it/s]
  4%|▍         | 98/2385 [01:39<34:40,  1.10it/s]
  4%|▍         | 99/2385 [01:40<36:30,  1.04it/s]
  4%|▍         | 100/2385 [01:41<36:11,  1.05it/s]
  4%|▍         | 101/2385 [01:42<35:52,  1.06it/s]
  4%|▍         | 102/2385 [01:43<35:42,  1.07it/s]
  4%|▍         | 103/2385 [01:44<35:18,  1.08it/s]
  4%|▍         | 104/2385 [01:45<41:28,  1.09s/it]
  4%|▍         | 105/2385 [01:46<41:03,  1.08s/it]
  4%|▍         | 106/2385 [01:47<39:10,  1.03s/it]
  4%|▍         | 107/2385 [01:49<41:36,  1.10s/it]
  5%|▍         | 108/2385 [01:49<39:31,  1.04s/it]
  5%|▍         | 109/2385 [01:51<39:52,  1.05s/it]
  5%|▍         | 110/2385 [01:51<38:03,  1.00s/it]
  5%|▍         | 111/2385 [01:52<36:52,  1.03it/s]
  5%|▍         | 112/2385 [01:53<36:00,  1.05it/s]
  5%|▍         | 113/2385 [01:54<35:29,  1.07it/s]
  5%|▍         | 114/2385 [01:55<35:44,  1.06it/s]
  5%|▍         | 115/2385 [01:56<35:41,  1.06it/s]
  5%|▍         | 116/2385 [01:57<35:06,  1.08it/s]
  5%|▍         | 117/2385 [01:58<34:47,  1.09it/s]
  5%|▍         | 118/2385 [01:59<34:19,  1.10it/s]
  5%|▍         | 119/2385 [02:00<34:08,  1.11it/s]
  5%|▌         | 120/2385 [02:01<36:02,  1.05it/s]
  5%|▌         | 121/2385 [02:02<35:56,  1.05it/s]
  5%|▌         | 122/2385 [02:02<35:21,  1.07it/s]
  5%|▌         | 123/2385 [02:04<36:33,  1.03it/s]
  5%|▌         | 124/2385 [02:04<36:05,  1.04it/s]
  5%|▌         | 125/2385 [02:05<35:34,  1.06it/s]
  5%|▌         | 126/2385 [02:06<35:07,  1.07it/s]
  5%|▌         | 127/2385 [02:07<34:42,  1.08it/s]
  5%|▌         | 128/2385 [02:08<34:42,  1.08it/s]
  5%|▌         | 129/2385 [02:09<36:20,  1.03it/s]
  5%|▌         | 130/2385 [02:10<35:38,  1.05it/s]
  5%|▌         | 131/2385 [02:11<35:37,  1.05it/s]
  6%|▌         | 132/2385 [02:12<35:09,  1.07it/s]
  6%|▌         | 133/2385 [02:13<36:33,  1.03it/s]
  6%|▌         | 134/2385 [02:14<35:44,  1.05it/s]
  6%|▌         | 135/2385 [02:15<35:07,  1.07it/s]
  6%|▌         | 136/2385 [02:16<34:32,  1.08it/s]
  6%|▌         | 137/2385 [02:17<34:29,  1.09it/s]
  6%|▌         | 138/2385 [02:18<34:18,  1.09it/s]
  6%|▌         | 139/2385 [02:18<34:01,  1.10it/s]
  6%|▌         | 140/2385 [02:19<34:28,  1.09it/s]
  6%|▌         | 141/2385 [02:20<34:06,  1.10it/s]
  6%|▌         | 142/2385 [02:21<35:40,  1.05it/s]
  6%|▌         | 143/2385 [02:22<35:03,  1.07it/s]
  6%|▌         | 144/2385 [02:23<34:35,  1.08it/s]
  6%|▌         | 145/2385 [02:24<34:09,  1.09it/s]
  6%|▌         | 146/2385 [02:25<33:53,  1.10it/s]
  6%|▌         | 147/2385 [02:26<33:56,  1.10it/s]
  6%|▌         | 148/2385 [02:27<33:42,  1.11it/s]
  6%|▌         | 149/2385 [02:28<34:48,  1.07it/s]
  6%|▋         | 150/2385 [02:29<34:18,  1.09it/s]
  6%|▋         | 151/2385 [02:30<38:21,  1.03s/it]
  6%|▋         | 152/2385 [02:31<37:14,  1.00s/it]
  6%|▋         | 153/2385 [02:32<36:16,  1.03it/s]
  6%|▋         | 154/2385 [02:33<35:51,  1.04it/s]
  6%|▋         | 155/2385 [02:34<35:16,  1.05it/s]
  7%|▋         | 156/2385 [02:35<35:12,  1.06it/s]
  7%|▋         | 157/2385 [02:35<35:14,  1.05it/s]
  7%|▋         | 158/2385 [02:36<34:38,  1.07it/s]
  7%|▋         | 159/2385 [02:37<34:10,  1.09it/s]
  7%|▋         | 160/2385 [02:38<33:46,  1.10it/s]
  7%|▋         | 161/2385 [02:39<35:40,  1.04it/s]
  7%|▋         | 162/2385 [02:40<35:02,  1.06it/s]
  7%|▋         | 163/2385 [02:41<34:16,  1.08it/s]
  7%|▋         | 164/2385 [02:42<33:45,  1.10it/s]
  7%|▋         | 165/2385 [02:43<33:28,  1.11it/s]
  7%|▋         | 166/2385 [02:44<33:21,  1.11it/s]
  7%|▋         | 167/2385 [02:45<33:11,  1.11it/s]
  7%|▋         | 168/2385 [02:45<33:03,  1.12it/s]
  7%|▋         | 169/2385 [02:46<33:01,  1.12it/s]
  7%|▋         | 170/2385 [02:47<34:47,  1.06it/s]
  7%|▋         | 171/2385 [02:48<34:26,  1.07it/s]
  7%|▋         | 172/2385 [02:49<34:04,  1.08it/s]
  7%|▋         | 173/2385 [02:50<34:31,  1.07it/s]
  7%|▋         | 174/2385 [02:51<34:15,  1.08it/s]
  7%|▋         | 175/2385 [02:52<34:08,  1.08it/s]
  7%|▋         | 176/2385 [02:53<33:45,  1.09it/s]
  7%|▋         | 177/2385 [02:54<34:19,  1.07it/s]
  7%|▋         | 178/2385 [02:55<31:44,  1.16it/s]
  8%|▊         | 179/2385 [02:55<29:58,  1.23it/s]
  8%|▊         | 180/2385 [02:56<28:31,  1.29it/s]
  8%|▊         | 181/2385 [02:57<27:33,  1.33it/s]
  8%|▊         | 182/2385 [02:57<26:55,  1.36it/s]
  8%|▊         | 183/2385 [02:58<26:53,  1.36it/s]
  8%|▊         | 184/2385 [02:59<26:27,  1.39it/s]
  8%|▊         | 185/2385 [02:59<26:08,  1.40it/s]
  8%|▊         | 186/2385 [03:00<25:59,  1.41it/s]
  8%|▊         | 187/2385 [03:01<25:49,  1.42it/s]
  8%|▊         | 188/2385 [03:02<25:36,  1.43it/s]
  8%|▊         | 189/2385 [03:02<25:23,  1.44it/s]
  8%|▊         | 190/2385 [03:03<25:23,  1.44it/s]
  8%|▊         | 191/2385 [03:04<25:17,  1.45it/s]
  8%|▊         | 192/2385 [03:04<25:16,  1.45it/s]
  8%|▊         | 193/2385 [03:05<25:20,  1.44it/s]
  8%|▊         | 194/2385 [03:06<26:20,  1.39it/s]
  8%|▊         | 195/2385 [03:06<26:02,  1.40it/s]
  8%|▊         | 196/2385 [03:07<27:25,  1.33it/s]
  8%|▊         | 197/2385 [03:08<26:52,  1.36it/s]
  8%|▊         | 198/2385 [03:09<26:20,  1.38it/s]
  8%|▊         | 199/2385 [03:09<26:01,  1.40it/s]
  8%|▊         | 200/2385 [03:10<25:56,  1.40it/s]
  8%|▊         | 201/2385 [03:11<25:56,  1.40it/s]
  8%|▊         | 202/2385 [03:12<25:41,  1.42it/s]
  9%|▊         | 203/2385 [03:12<25:32,  1.42it/s]
  9%|▊         | 204/2385 [03:13<25:53,  1.40it/s]
  9%|▊         | 205/2385 [03:14<25:50,  1.41it/s]
  9%|▊         | 206/2385 [03:14<25:41,  1.41it/s]
  9%|▊         | 207/2385 [03:15<25:47,  1.41it/s]
  9%|▊         | 208/2385 [03:16<25:48,  1.41it/s]
  9%|▉         | 209/2385 [03:16<25:36,  1.42it/s]
  9%|▉         | 210/2385 [03:17<25:40,  1.41it/s]
  9%|▉         | 211/2385 [03:18<25:32,  1.42it/s]
  9%|▉         | 212/2385 [03:19<25:28,  1.42it/s]
  9%|▉         | 213/2385 [03:19<25:29,  1.42it/s]
  9%|▉         | 214/2385 [03:20<25:33,  1.42it/s]
  9%|▉         | 215/2385 [03:21<25:44,  1.41it/s]
  9%|▉         | 216/2385 [03:21<25:41,  1.41it/s]
  9%|▉         | 217/2385 [03:22<25:25,  1.42it/s]
  9%|▉         | 218/2385 [03:23<25:15,  1.43it/s]
  9%|▉         | 219/2385 [03:24<25:40,  1.41it/s]
  9%|▉         | 220/2385 [03:24<25:23,  1.42it/s]
  9%|▉         | 221/2385 [03:25<25:09,  1.43it/s]
  9%|▉         | 222/2385 [03:26<25:02,  1.44it/s]
  9%|▉         | 223/2385 [03:26<26:44,  1.35it/s]
  9%|▉         | 224/2385 [03:27<26:05,  1.38it/s]
  9%|▉         | 225/2385 [03:28<26:42,  1.35it/s]
  9%|▉         | 226/2385 [03:29<26:01,  1.38it/s]
 10%|▉         | 227/2385 [03:29<25:41,  1.40it/s]
 10%|▉         | 228/2385 [03:30<25:53,  1.39it/s]
 10%|▉         | 229/2385 [03:31<25:32,  1.41it/s]
 10%|▉         | 230/2385 [03:31<25:18,  1.42it/s]
 10%|▉         | 231/2385 [03:32<25:57,  1.38it/s]
 10%|▉         | 232/2385 [03:33<25:41,  1.40it/s]
 10%|▉         | 233/2385 [03:34<25:41,  1.40it/s]
 10%|▉         | 234/2385 [03:34<25:34,  1.40it/s]
 10%|▉         | 235/2385 [03:35<25:32,  1.40it/s]
 10%|▉         | 236/2385 [03:36<25:58,  1.38it/s]
 10%|▉         | 237/2385 [03:37<26:03,  1.37it/s]
 10%|▉         | 238/2385 [03:37<25:57,  1.38it/s]
 10%|█         | 239/2385 [03:38<25:53,  1.38it/s]
 10%|█         | 240/2385 [03:39<25:33,  1.40it/s]
 10%|█         | 241/2385 [03:39<25:24,  1.41it/s]
 10%|█         | 242/2385 [03:40<25:27,  1.40it/s]
 10%|█         | 243/2385 [03:41<25:12,  1.42it/s]
 10%|█         | 244/2385 [03:41<25:17,  1.41it/s]
 10%|█         | 245/2385 [03:42<27:36,  1.29it/s]
 10%|█         | 246/2385 [03:43<27:07,  1.31it/s]
 10%|█         | 247/2385 [03:44<26:22,  1.35it/s]
 10%|█         | 248/2385 [03:45<25:59,  1.37it/s]
 10%|█         | 249/2385 [03:46<28:41,  1.24it/s]
 10%|█         | 250/2385 [03:46<27:50,  1.28it/s]
 11%|█         | 251/2385 [03:47<27:58,  1.27it/s]
 11%|█         | 252/2385 [03:48<27:07,  1.31it/s]
 11%|█         | 253/2385 [03:48<26:21,  1.35it/s]
 11%|█         | 254/2385 [03:49<25:56,  1.37it/s]
 11%|█         | 255/2385 [03:50<25:39,  1.38it/s]
 11%|█         | 256/2385 [03:51<25:16,  1.40it/s]
 11%|█         | 257/2385 [03:51<25:00,  1.42it/s]
 11%|█         | 258/2385 [03:52<24:57,  1.42it/s]
 11%|█         | 259/2385 [03:53<25:36,  1.38it/s]
 11%|█         | 260/2385 [03:53<25:21,  1.40it/s]
 11%|█         | 261/2385 [03:54<25:03,  1.41it/s]
 11%|█         | 262/2385 [03:55<24:55,  1.42it/s]
 11%|█         | 263/2385 [03:55<24:50,  1.42it/s]
 11%|█         | 264/2385 [03:56<24:50,  1.42it/s]
 11%|█         | 265/2385 [03:57<27:53,  1.27it/s]
 11%|█         | 266/2385 [03:58<26:57,  1.31it/s]
 11%|█         | 267/2385 [03:59<26:18,  1.34it/s]
 11%|█         | 268/2385 [03:59<25:44,  1.37it/s]
 11%|█▏        | 269/2385 [04:00<25:19,  1.39it/s]
 11%|█▏        | 270/2385 [04:01<24:59,  1.41it/s]
 11%|█▏        | 271/2385 [04:01<24:55,  1.41it/s]
 11%|█▏        | 272/2385 [04:02<24:46,  1.42it/s]
 11%|█▏        | 273/2385 [04:03<24:53,  1.41it/s]
 11%|█▏        | 274/2385 [04:03<24:42,  1.42it/s]
 12%|█▏        | 275/2385 [04:04<24:32,  1.43it/s]
 12%|█▏        | 276/2385 [04:05<24:22,  1.44it/s]
 12%|█▏        | 277/2385 [04:05<24:16,  1.45it/s]
 12%|█▏        | 278/2385 [04:06<24:17,  1.45it/s]
 12%|█▏        | 279/2385 [04:07<24:16,  1.45it/s]
 12%|█▏        | 280/2385 [04:08<24:18,  1.44it/s]
 12%|█▏        | 281/2385 [04:08<24:17,  1.44it/s]
 12%|█▏        | 282/2385 [04:09<24:17,  1.44it/s]
 12%|█▏        | 283/2385 [04:10<25:04,  1.40it/s]
 12%|█▏        | 284/2385 [04:10<24:50,  1.41it/s]
 12%|█▏        | 285/2385 [04:11<24:36,  1.42it/s]
 12%|█▏        | 286/2385 [04:12<25:06,  1.39it/s]
 12%|█▏        | 287/2385 [04:13<25:50,  1.35it/s]
 12%|█▏        | 288/2385 [04:13<25:17,  1.38it/s]
 12%|█▏        | 289/2385 [04:14<26:03,  1.34it/s]
 12%|█▏        | 290/2385 [04:15<25:23,  1.38it/s]
 12%|█▏        | 291/2385 [04:16<25:27,  1.37it/s]
 12%|█▏        | 292/2385 [04:16<24:58,  1.40it/s]
 12%|█▏        | 293/2385 [04:17<24:40,  1.41it/s]
 12%|█▏        | 294/2385 [04:18<24:48,  1.40it/s]
 12%|█▏        | 295/2385 [04:18<24:41,  1.41it/s]
 12%|█▏        | 296/2385 [04:19<24:31,  1.42it/s]
 12%|█▏        | 297/2385 [04:20<24:26,  1.42it/s]
 12%|█▏        | 298/2385 [04:20<24:15,  1.43it/s]
 13%|█▎        | 299/2385 [04:21<24:10,  1.44it/s]
 13%|█▎        | 300/2385 [04:22<24:38,  1.41it/s]
 13%|█▎        | 301/2385 [04:23<24:22,  1.42it/s]
 13%|█▎        | 302/2385 [04:23<24:29,  1.42it/s]
 13%|█▎        | 303/2385 [04:24<24:44,  1.40it/s]
 13%|█▎        | 304/2385 [04:25<24:28,  1.42it/s]
 13%|█▎        | 305/2385 [04:25<24:14,  1.43it/s]
 13%|█▎        | 306/2385 [04:26<24:13,  1.43it/s]
 13%|█▎        | 307/2385 [04:27<24:07,  1.44it/s]
 13%|█▎        | 308/2385 [04:28<27:52,  1.24it/s]
 13%|█▎        | 309/2385 [04:29<28:58,  1.19it/s]
 13%|█▎        | 310/2385 [04:29<27:33,  1.25it/s]
 13%|█▎        | 311/2385 [04:30<26:32,  1.30it/s]
 13%|█▎        | 312/2385 [04:31<25:44,  1.34it/s]
 13%|█▎        | 313/2385 [04:32<25:11,  1.37it/s]
 13%|█▎        | 314/2385 [04:32<25:06,  1.37it/s]
 13%|█▎        | 315/2385 [04:33<24:46,  1.39it/s]
 13%|█▎        | 316/2385 [04:34<24:24,  1.41it/s]
 13%|█▎        | 317/2385 [04:35<26:22,  1.31it/s]
 13%|█▎        | 318/2385 [04:35<25:31,  1.35it/s]
 13%|█▎        | 319/2385 [04:36<25:02,  1.37it/s]
 13%|█▎        | 320/2385 [04:37<24:38,  1.40it/s]
 13%|█▎        | 321/2385 [04:37<24:23,  1.41it/s]
 14%|█▎        | 322/2385 [04:38<24:17,  1.42it/s]
 14%|█▎        | 323/2385 [04:39<24:14,  1.42it/s]
 14%|█▎        | 324/2385 [04:39<24:05,  1.43it/s]
 14%|█▎        | 325/2385 [04:40<24:07,  1.42it/s]
 14%|█▎        | 326/2385 [04:41<24:09,  1.42it/s]
 14%|█▎        | 327/2385 [04:41<23:54,  1.43it/s]
 14%|█▍        | 328/2385 [04:42<23:50,  1.44it/s]
 14%|█▍        | 329/2385 [04:43<23:50,  1.44it/s]
 14%|█▍        | 330/2385 [04:44<24:36,  1.39it/s]
 14%|█▍        | 331/2385 [04:44<24:17,  1.41it/s]
 14%|█▍        | 332/2385 [04:45<24:02,  1.42it/s]
 14%|█▍        | 333/2385 [04:46<23:54,  1.43it/s]
 14%|█▍        | 334/2385 [04:46<23:59,  1.42it/s]
 14%|█▍        | 335/2385 [04:47<23:48,  1.43it/s]
 14%|█▍        | 336/2385 [04:48<23:47,  1.44it/s]
 14%|█▍        | 337/2385 [04:48<23:44,  1.44it/s]
 14%|█▍        | 338/2385 [04:49<23:41,  1.44it/s]
 14%|█▍        | 339/2385 [04:50<23:32,  1.45it/s]
 14%|█▍        | 340/2385 [04:51<23:30,  1.45it/s]
 14%|█▍        | 341/2385 [04:51<23:31,  1.45it/s]
 14%|█▍        | 342/2385 [04:52<23:43,  1.43it/s]
 14%|█▍        | 343/2385 [04:53<23:41,  1.44it/s]
 14%|█▍        | 344/2385 [04:53<25:14,  1.35it/s]
 14%|█▍        | 345/2385 [04:54<24:43,  1.38it/s]
 15%|█▍        | 346/2385 [04:55<24:17,  1.40it/s]
 15%|█▍        | 347/2385 [04:56<24:03,  1.41it/s]
 15%|█▍        | 348/2385 [04:56<23:51,  1.42it/s]
 15%|█▍        | 349/2385 [04:57<23:58,  1.42it/s]
 15%|█▍        | 350/2385 [04:58<23:49,  1.42it/s]
 15%|█▍        | 351/2385 [04:58<23:37,  1.43it/s]
 15%|█▍        | 352/2385 [04:59<23:31,  1.44it/s]
 15%|█▍        | 353/2385 [05:00<24:05,  1.41it/s]
 15%|█▍        | 354/2385 [05:00<24:05,  1.41it/s]
 15%|█▍        | 355/2385 [05:01<25:29,  1.33it/s]
 15%|█▍        | 356/2385 [05:02<24:53,  1.36it/s]
 15%|█▍        | 357/2385 [05:03<24:37,  1.37it/s]
 15%|█▌        | 358/2385 [05:03<24:21,  1.39it/s]
 15%|█▌        | 359/2385 [05:04<24:06,  1.40it/s]
 15%|█▌        | 360/2385 [05:05<23:52,  1.41it/s]
 15%|█▌        | 361/2385 [05:06<23:39,  1.43it/s]
 15%|█▌        | 362/2385 [05:06<23:38,  1.43it/s]
 15%|█▌        | 363/2385 [05:07<23:36,  1.43it/s]
 15%|█▌        | 364/2385 [05:08<23:30,  1.43it/s]
 15%|█▌        | 365/2385 [05:08<23:27,  1.44it/s]
 15%|█▌        | 366/2385 [05:09<23:31,  1.43it/s]
 15%|█▌        | 367/2385 [05:10<23:40,  1.42it/s]
 15%|█▌        | 368/2385 [05:11<25:11,  1.33it/s]
 15%|█▌        | 369/2385 [05:11<24:56,  1.35it/s]
 16%|█▌        | 370/2385 [05:12<24:47,  1.35it/s]
 16%|█▌        | 371/2385 [05:13<25:30,  1.32it/s]
 16%|█▌        | 372/2385 [05:14<25:01,  1.34it/s]
 16%|█▌        | 373/2385 [05:14<24:52,  1.35it/s]
 16%|█▌        | 374/2385 [05:15<24:32,  1.37it/s]
 16%|█▌        | 375/2385 [05:16<24:05,  1.39it/s]
 16%|█▌        | 376/2385 [05:16<23:45,  1.41it/s]
 16%|█▌        | 377/2385 [05:17<23:31,  1.42it/s]
 16%|█▌        | 378/2385 [05:18<23:27,  1.43it/s]
 16%|█▌        | 379/2385 [05:18<23:21,  1.43it/s]
 16%|█▌        | 380/2385 [05:19<25:02,  1.33it/s]
 16%|█▌        | 381/2385 [05:20<24:29,  1.36it/s]
 16%|█▌        | 382/2385 [05:21<24:10,  1.38it/s]
 16%|█▌        | 383/2385 [05:21<23:48,  1.40it/s]
 16%|█▌        | 384/2385 [05:22<23:32,  1.42it/s]
 16%|█▌        | 385/2385 [05:23<23:40,  1.41it/s]
 16%|█▌        | 386/2385 [05:24<23:38,  1.41it/s]
 16%|█▌        | 387/2385 [05:24<23:34,  1.41it/s]
 16%|█▋        | 388/2385 [05:25<23:27,  1.42it/s]
 16%|█▋        | 389/2385 [05:26<23:16,  1.43it/s]
 16%|█▋        | 390/2385 [05:26<23:11,  1.43it/s]
 16%|█▋        | 391/2385 [05:27<23:13,  1.43it/s]
 16%|█▋        | 392/2385 [05:28<24:51,  1.34it/s]
 16%|█▋        | 393/2385 [05:29<24:21,  1.36it/s]

,docno,snippet,title,main_content,readability,obj_prob,edu_val
0,6e421f1539b1457b853712d81be87743,WEBBTS (also Bangtan Boys; Korean: 방탄소년단 Bangt...,BTS (band) - Wikipedia,BTS (also Bangtan Boys; Korean: 방탄소년단 Bangtan ...,8.476857,0.876282,1
1,1539268e3f1d41c9abcaa277b23f51d9,WEBMusic video by BTS performing Dynamite. (C)...,Before you go on to YouTube,YouTube\nA Google company\n\nBefore you go on ...,5.729500,0.846696,0
2,93689ea1c0ec4272b41d7b259cb47890,Biography BTS is a Grammy-nominated South Kore...,Before you go on to YouTube,YouTube\nA Google company\n\nBefore you go on ...,6.051250,0.895289,1
3,2e4321c5105840c8b6612f87dc4aba13,WEBBTS (Korean: 방탄소년단; RR: Bangtan Sonyeondan;...,BTS - Wikipedia,BTS (Korean방탄소년단; RRBangtan Sonyeondan; lit. B...,6.293952,0.876808,1
4,3d21474fff4e406c9db2984d5edf647b,"WEBTo avoid this, cancel and sign in to YouTub...",BTS (방탄소년단) 'Yet To Come (The Most Beautiful M...,"So, Who is missing BTS badly. Let's stay stron...",5.167517,0.615062,0

## Creating other versions of ground truth

### Relevance + Readability

In [10]:
# binary readability relevance: same query-doc pairs as qrels-relevance-binary.txt 
# query-doc pair assigned 1 if relevant and readable; 0 otherwise

from tqdm import tqdm
import pandas as pd

# nltk.download('all', halt_on_error=False)
corpus = pd.read_csv("../data/kid-friend-en/en/inputs/documents.csv")
qrels_df = pd.read_csv("../data/kid-friend-en/en/qrels/qrels-relevance-binary.csv")
read_relevance = []
issue_docs = []

for _, row in tqdm(qrels_df.iterrows(), total=len(qrels_df)):
    qid = row["qid"]
    docid = row["docno"]
    relevance = row["relevance"]
    readability = list(corpus.loc[corpus["docno"]==docid]["readability"])[0]
    if readability < 0: # removing query-doc pairs where the readability score is invalid (i.e., the score < 0)
        issue_docs.append(docid)
        continue
    else:
        read_relevance.append([qid, "q0", docid, relevance*int(int(readability)<=4)])

qrels_readability_df = pd.DataFrame(read_relevance, columns=["qid", "q0", "docno", "relevance"])
qrels_readability_df.to_csv("../data/kid-friend-en/en/qrels/qrels-readability-binary.csv", index=False)
qrels_readability_df

  0%|          | 0/2303 [00:00<?, ?it/s]
 12%|█▏        | 271/2303 [00:00<00:00, 2706.30it/s]
 24%|██▍       | 555/2303 [00:00<00:00, 2782.97it/s]
 37%|███▋      | 848/2303 [00:00<00:00, 2846.96it/s]
 50%|████▉     | 1140/2303 [00:00<00:00, 2873.79it/s]
 62%|██████▏   | 1436/2303 [00:00<00:00, 2902.30it/s]
 75%|███████▍  | 1727/2303 [00:00<00:00, 2894.81it/s]
100%|██████████| 2303/2303 [00:00<00:00, 2876.85it/s]

      qid  q0                             docno  relevance
0       1  q0  77cdd0f6c3b04b5bbe79fac37c2ae63b          0
1       1  q0  c8a2aa042145402a8c180ca6f467c575          0
2       1  q0  d82e5e4f531841d49bcd6fe7bd8cdf8f          0
3       1  q0  c8e3ba8d611441bebaf146001171af3a          0
4       1  q0  44d7a109cd554b1cb44d2c3867ff7040          0
...   ...  ..                               ...        ...
2211   50  q0  b7646dcb4b134afbacbe9a61a4ef914e          1
2212   50  q0  bc5f268885cb41379f06ced62f96adbb          0
2213   50  q0  c5840e5e858d4baa97ecf216dda4e6c3          0
2214   50  q0  bf5f2ac9b4454a79bd6848f10314bbee          0
2215   50  q0  e4adf192c95d4114a131174f6df262dd          1

[2216 rows x 4 columns]

In [11]:
assert (len(qrels_df)-len(qrels_readability_df))==len(issue_docs)

doc_issues = [x for x in list(qrels_df["docno"].unique()) if x not in list(qrels_readability_df["docno"].unique())]
print(len(doc_issues), len(set(issue_docs)))
for docno in doc_issues:
    print(docno, list(corpus.loc[corpus["docno"]==docno]["readability"])[0])

81 81
3cca2583656a4c528dcc6b8213b5bdd7 -1.0
ec742a5f53bf4c6db7aafdc361afbf61 -1.0
69153b48fc8a49d0b25288ff437c3710 -1.0
02cd6a52f92847d491ef13d36f42b2a6 -1.0
2357bd4bfba440cfbe6d86c66211ea63 -1.0
ad5c1a75ba0b47e58fcdfef8471a2cf7 -1.0
774e9cd59abb48d3a2687f0dc25f7156 -1.0
815e9f8e2ccd441491e7b1c1f2a05d49 -1.0
e800b727c5ff4395900c3078ed2752e6 -1.0
71b8acf3a6164762a2b044e8e763f05f -1.0
11c4c5258e8945309209c7156c24d3e0 -1.0
8cccf65c62d4458cb6934a2c678cf630 -1.0
527da37320224a27a37c93f125731db9 -1.0
e8653177217b4dbda0e9371de924675a -1.0
3b426dd868e1458eacc3c9fe8fe489e5 -1.0
fa974baf472e4443abafc3523d6e58fb -1.0
340c35086579401aa090a995e8cc6fb8 -1.0
bcb4bb8d25ab482b81e9fe51d0824092 -1.0
011f2d15eaf24cae9fa91666fd108458 -1.0
785d82f6d995495baac1586e2f92e7ba -1.0
3cd906efb7a24dbfade7214b87ebf365 -1.0
102463237fc9478ea8c107772539cdf9 -1.0
75e3dd963a054efb9aa73db8c9480502 -1.0
849bfea1e63e415cb5464341d83b9fc5 -1.0
a229b0bd3e7742be8f69820b3bc993f8 -1.0
2529ae2c690d4294b307f9b05b25f26d -1.0
6574ea3918954a478429d1227e1e16a5 -1.0
5370163e03cc4fd7b3003e08cd95c12f -1.0
d3653e61dbb1429cac52137ee3d625e6 -1.0
d9a7d6b24a0a437c8f656013b71ae5da -1.0
3351d27c84c74e429950fd8321ab0107 -1.0
d4ae8202e4644e0990fb184d8cf5eaa0 -1.0
2fa90be31a6a413bbfd64c94013b69f5 -1.0
1788830699954d27b7055b93ed0485ea -1.0
7ca1d5485c244228aeecb272a9597eb6 -1.0
6631c7692a2148beae63c0bdb6c82e70 -1.0
15dec58f368f42e6870a5697d3678c7d -1.0
3100f7d1a7fe404d848789f0dd4b215d -1.0
7ff9d02a347e40778dc48bc703491d36 -1.0
d9d43fa8cd6942c18e3d1cff78085794 -1.0
5f188fe387f049e1a8db34fabe94a917 -1.0
69164ecf7a66448cbce7f3fd401ca0b0 -1.0
c6fedef2e95144228cc98fc7cbf5fd7f -1.0
26384f5e770143cb9b87fbe0af31b401 -1.0
be0f2f32c058491cbcc6bc688114e7b0 -1.0
e23c426ff4da49e7b84e3eff9dfdff57 -1.0
35f1fb9b15a04464b5c710a37d114b72 -1.0
fdb6fd6a14d444a3a6fa9cb69cc6075b -1.0
e4710f39382f4736ba1460d89180a252 -1.0
cc84cff0ce574c6ca083469794a2be92 -1.0
00430512355b4c658c6f3abdc26eda03 -1.0
1cabf3ca3e7a4211ae6775bd07502f9d -1.0
66e24a40a035429cb2b0fc0330c421f3 -1.0
4b1afb83acd641ff83dfc42ce3c8b4eb -1.0
17c028fce0464d2699caa5a462327d44 -1.0
965b8967b289492bac4c2098d0c2d6c9 -1.0
bff172f8224249679551a7e4574f1c85 -1.0
8e08f57d3094457d8e6acd33a2a246c4 -1.0
5aff36b447a7406eb9501a4d1e7ac84e -1.0
a98edde6252d46efadd77fa648656c94 -1.0
f50d077d16264fb2a8b91ebdc31abc54 -1.0
0475a03b49044104b93d0947dd284b86 -1.0
5387377f744e4ea3ac241f05966afb33 -1.0
b0687fecdf9d477e833963defdf74e10 -1.0
8b7a9da26fb64480a8003fede84a555a -1.0
1ab44d8d8ed14866a202c7670ed7ee77 -1.0
d0f3d5c0bd1a4555ab450f158a352332 -1.0
adf1a1423f6e4114b4e67b68d6da84cc -1.0
161338fc0d0c4385a973f9d861940566 -1.0
30ac104c823a49729a873ea581aea6cf -1.0
4a9156f6fd9b44f9b6eae578913a368c -1.0
270ab4fb8a474ec3a5971934fb9e2a87 -1.0
58ae98ccd0534461af58b6c8faa6ab0c -1.0
3fcf27e780f147ae96e799b5e3832615 -1.0
9b416a567f5b4bb0bc2ce99cd2ab1e25 -1.0
02c82fe2db8746ac8e6789efac91e823 -1.0
3a667ab4ded14e8891d0180e2944a1bb -1.0
ae64d77ebaf74ee1839dc1557defa3a3 -1.0
c2a251b89e224009ac1765bf4dd1d395 -1.0
333fdd2f08234b25a2a61b44470cad01 -1.0
db2c3a6083564168ba7e5ae615ecbd9d -1.0

### Objectivity + Relevance

In [13]:
import json
import pandas as pd
from utils import pred_obj
from tqdm import tqdm

lines = []
with open(r'../data/kid-friend-en/en/inputs/documents.jsonl') as f:
    lines = f.read().splitlines()

line_dicts = [json.loads(line) for line in lines]
corpus = pd.DataFrame(line_dicts)
corpus.drop_duplicates(inplace=True,ignore_index=True)
corpus["obj_prob"] = pred_obj(list(corpus["snippet"]))

# corpus.head()

qrels_df = pd.read_csv("../data/kid-friend-en/en/qrels/qrels-relevance-binary.csv")
obj_relevance = []
issue_docs = []

for _, row in tqdm(qrels_df.iterrows(), total=len(qrels_df)):
    qid = row["qid"]
    docid = row["docno"]
    relevance = row["relevance"]
    objectivity = list(corpus.loc[corpus["docno"]==docid]["obj_prob"])[0]
    obj_relevance.append([qid, "q0", docid, relevance*objectivity])

qrels_objectivity_df = pd.DataFrame(obj_relevance, columns=["qid", "q0", "docno", "relevance"])
qrels_objectivity_df.to_csv("../data/kid-friend-en/en/qrels/qrels-objectivity-binary.csv", index=False)
qrels_objectivity_df

Device set to use cuda:0

  0%|          | 0/2303 [00:00<?, ?it/s]
 12%|█▏        | 283/2303 [00:00<00:00, 2826.00it/s]
 25%|██▌       | 576/2303 [00:00<00:00, 2885.31it/s]
 38%|███▊      | 868/2303 [00:00<00:00, 2899.18it/s]
 51%|█████     | 1174/2303 [00:00<00:00, 2959.16it/s]
 64%|██████▍   | 1480/2303 [00:00<00:00, 2995.23it/s]
 77%|███████▋  | 1780/2303 [00:00<00:00, 2976.55it/s]
100%|██████████| 2303/2303 [00:00<00:00, 2941.39it/s]

      qid  q0                             docno  relevance
0       1  q0  77cdd0f6c3b04b5bbe79fac37c2ae63b          0
1       1  q0  c8a2aa042145402a8c180ca6f467c575          1
2       1  q0  d82e5e4f531841d49bcd6fe7bd8cdf8f          0
3       1  q0  c8e3ba8d611441bebaf146001171af3a          1
4       1  q0  44d7a109cd554b1cb44d2c3867ff7040          1
...   ...  ..                               ...        ...
2298   50  q0  b7646dcb4b134afbacbe9a61a4ef914e          0
2299   50  q0  bc5f268885cb41379f06ced62f96adbb          0
2300   50  q0  c5840e5e858d4baa97ecf216dda4e6c3          0
2301   50  q0  bf5f2ac9b4454a79bd6848f10314bbee          0
2302   50  q0  e4adf192c95d4114a131174f6df262dd          1

[2303 rows x 4 columns]

### Educational Alignment + Relevance

In [12]:
from tqdm import tqdm
import pandas as pd

corpus = pd.read_csv("../data/kid-friend-en/en/inputs/documents.csv")
qrels_df = pd.read_csv("../data/kid-friend-en/en/qrels/qrels-relevance-binary.csv")
edu_relevance = []
issue_docs = []

for _, row in tqdm(qrels_df.iterrows(), total=len(qrels_df)):
    qid = row["qid"]
    docid = row["docno"]
    relevance = row["relevance"]
    edu_val = list(corpus.loc[corpus["docno"]==docid]["edu_val"])[0]
    edu_relevance.append([qid, "q0", docid, relevance*int(edu_val>=3)])

qrels_edu_df = pd.DataFrame(edu_relevance, columns=["qid", "q0", "docno", "relevance"])
qrels_edu_df.to_csv("../data/kid-friend-en/en/qrels/qrels-edu-binary.csv", index=False)
qrels_edu_df

  0%|          | 0/2303 [00:00<?, ?it/s]
 12%|█▏        | 282/2303 [00:00<00:00, 2815.04it/s]
 25%|██▍       | 570/2303 [00:00<00:00, 2847.42it/s]
 37%|███▋      | 858/2303 [00:00<00:00, 2861.74it/s]
 50%|████▉     | 1145/2303 [00:00<00:00, 2862.97it/s]
 62%|██████▏   | 1439/2303 [00:00<00:00, 2890.05it/s]
 75%|███████▌  | 1729/2303 [00:00<00:00, 2888.26it/s]
100%|██████████| 2303/2303 [00:00<00:00, 2875.58it/s]

      qid  q0                             docno  relevance
0       1  q0  77cdd0f6c3b04b5bbe79fac37c2ae63b          0
1       1  q0  c8a2aa042145402a8c180ca6f467c575          0
2       1  q0  d82e5e4f531841d49bcd6fe7bd8cdf8f          0
3       1  q0  c8e3ba8d611441bebaf146001171af3a          0
4       1  q0  44d7a109cd554b1cb44d2c3867ff7040          0
...   ...  ..                               ...        ...
2298   50  q0  b7646dcb4b134afbacbe9a61a4ef914e          0
2299   50  q0  bc5f268885cb41379f06ced62f96adbb          0
2300   50  q0  c5840e5e858d4baa97ecf216dda4e6c3          0
2301   50  q0  bf5f2ac9b4454a79bd6848f10314bbee          0
2302   50  q0  e4adf192c95d4114a131174f6df262dd          0

[2303 rows x 4 columns]